### PR TITLE
Add intersphinx mapping for gallery -> doc and fix gallery titlebar links

### PR DESCRIPTION
**Pull request by ketch**
With this commit, I believe everything works correctly when one builds the docs locally.  This includes:

- Links in the bar at the top of the page, both from the gallery to the docs and from the docs to the gallery
- Sphinx references (both directions)

However, I believe these links won't work correctly when pushed to the web, since they explicitly contain `_build/html` in the paths.  What would be ideal is

- Have two targets in the Makefile: one for a local build, one for publishing to the web.
- Each target sets an environment variable to a different value.
- In conf.py, we check this environment variable and set the intersphinx mapping and the links in the top bar accordingly.

### CODE REVIEW

**Comment by rjleveque** [comment]
I'll test this out soon.

We also probably want to use sphinx-versioning when building for the web but perhaps not locally?

**Comment by ketch** [comment]
>We also probably want to use sphinx-versioning when building for the web but perhaps not locally?

Sounds right.  Although really it should only be necessary to redo that when there is a release.

**Comment by rjleveque** [comment]
@ketch:  Links to Jupyter notebooks work from the TOCs, e.g. in `geoclaw.rst` but not when cited as :ref:`geoclaw/topotools_examples.ipynb`, e.g. the links of this form from `notebooks.rst` seem to all be broken.

**Comment by rjleveque** [comment]
Ok, I think I got this working for both headers and cross-references of sections.

Set the environment variable `SPHINX_WEB` to `True` before doing `make html` for the webpage versions.  I just pushed the results to http://www.clawpack.org/ and I think it's all ok.

If you set this environment variable to anything else or it is unset, then it should make a version that works locally.  

Note you have to do `make html` in both `doc/doc` and `doc/gallery` with the same setting for things to work well together.

It seems to redo everything, probably because I always overwrite `_themes/flask/layout.html` as part of what's done in the `Makefile`, so everything is stale.  There's probably a better way to do this.

**Pull request merged**
